package virusscan

import (
	"fmt"
	"regexp"
	"strings"
	"time"
)

var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)
var drivePath = regexp.MustCompile(`^[a-zA-Z]:[\\/]`)

func ValidID(id string) bool { return uuidPattern.MatchString(id) }

type Request struct {
	AgentIDs  []string `json:"agent_ids,omitempty"`
	JobID     string   `json:"job_id,omitempty"`
	Type      string   `json:"type"`
	AgentID   string   `json:"agent_id"`
	ScanType  string   `json:"scan_type"`
	Path      string   `json:"path,omitempty"`
	RequestID string   `json:"request_id,omitempty"`
	Limit     int      `json:"limit,omitempty"`
}

func (r Request) Validate() error {
	if _, err := r.TargetIDs(); err != nil {
		return err
	}
	if r.RequestID != "" || r.JobID != "" {
		return fmt.Errorf("request_id and job_id are generated by the server")
	}
	if r.ScanType != "quick" && r.ScanType != "full" && r.ScanType != "custom" {
		return fmt.Errorf("scan_type must be quick, full, or custom")
	}
	if r.ScanType != "custom" {
		if r.Path != "" {
			return fmt.Errorf("path is only allowed for custom scans")
		}
		return nil
	}
	if len(r.Path) > 32767 || strings.ContainsAny(r.Path, "*?\x00\r\n") {
		return fmt.Errorf("invalid custom path")
	}
	unc := strings.Split(strings.TrimPrefix(r.Path, `\\`), `\`)
	if !drivePath.MatchString(r.Path) && !(strings.HasPrefix(r.Path, `\\`) && len(unc) >= 2 && unc[0] != "" && unc[0] != "." && unc[1] != "") {
		return fmt.Errorf("custom path must be an absolute Windows path")
	}
	return nil
}

// TargetIDs accepts the original single-agent API or a bounded, distinct set of agents.
func (r Request) TargetIDs() ([]string, error) {
	if r.AgentID != "" && len(r.AgentIDs) > 0 {
		return nil, fmt.Errorf("use agent_id or agent_ids, not both")
	}
	ids := r.AgentIDs
	if r.AgentID != "" {
		ids = []string{r.AgentID}
	}
	if len(ids) == 0 || len(ids) > 100 {
		return nil, fmt.Errorf("provide 1 to 100 agents")
	}
	seen := map[string]bool{}
	result := make([]string, 0, len(ids))
	for _, id := range ids {
		if !ValidID(id) {
			return nil, fmt.Errorf("invalid agent_id")
		}
		id = strings.ToLower(id)
		if seen[id] {
			return nil, fmt.Errorf("duplicate agent_id")
		}
		seen[id] = true
		result = append(result, id)
	}
	return result, nil
}

type Target struct {
	AgentID   string `json:"agent_id"`
	RequestID string `json:"request_id"`
	Dispatch  string `json:"dispatch,omitempty"`
}
type Job struct {
	ID      string   `json:"job_id"`
	Targets []Target `json:"targets"`
}

type Report struct {
	ExitCode        int    `json:"exit_code"`
	Output          string `json:"output"`
	OutputTruncated bool   `json:"output_truncated"`
}
type Event struct {
	Type       string     `json:"type"`
	RequestID  string     `json:"request_id"`
	ScanType   string     `json:"scan_type"`
	Status     string     `json:"status"`
	StartedAt  *time.Time `json:"started_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Report     *Report    `json:"report,omitempty"`
	Error      string     `json:"error,omitempty"`
}

func (e Event) Validate() error {
	if !ValidID(e.RequestID) {
		return fmt.Errorf("invalid request_id")
	}
	if e.ScanType != "quick" && e.ScanType != "full" && e.ScanType != "custom" {
		return fmt.Errorf("invalid scan_type")
	}
	if e.Type == "virus_scan_status" {
		if e.Status != "running" || e.StartedAt == nil || e.FinishedAt != nil || e.Report != nil {
			return fmt.Errorf("invalid running event")
		}
	} else if e.Type == "virus_scan_result" {
		if e.Status != "completed" && e.Status != "failed" && e.Status != "rejected" && e.Status != "cancelled" {
			return fmt.Errorf("invalid final status")
		}
		if e.FinishedAt == nil {
			return fmt.Errorf("finished_at required")
		}
		if e.Status == "completed" && (e.Report == nil || e.Report.ExitCode != 0 || e.StartedAt == nil) {
			return fmt.Errorf("invalid completed report")
		}
	} else {
		return fmt.Errorf("invalid event type")
	}
	if e.Report != nil && len(e.Report.Output) > 128*1024 {
		return fmt.Errorf("report too large")
	}
	if len(e.Error) > 32768 {
		return fmt.Errorf("error too large")
	}
	if e.StartedAt != nil && e.FinishedAt != nil && e.FinishedAt.Before(*e.StartedAt) {
		return fmt.Errorf("invalid timestamps")
	}
	return nil
}

type Record struct {
	JobID      string     `json:"job_id"`
	Message    string     `json:"message,omitempty"`
	RequestID  string     `json:"request_id"`
	AgentID    string     `json:"agent_id"`
	ScanType   string     `json:"scan_type"`
	Path       string     `json:"path,omitempty"`
	Status     string     `json:"status"`
	CreatedAt  time.Time  `json:"created_at"`
	StartedAt  *time.Time `json:"started_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Result     *Event     `json:"result,omitempty"`
}
